# Generated by Django 3.2.7 on 2021-10-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.FileField(storage='/Users/cyrilhenry/Documents/PYTHON/school/school/content/mediaword/', upload_to='word/'),
        ),
    ]
