# Generated by Django 3.2.7 on 2021-10-05 19:04

from django.db import migrations, models
import games.storage


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_word_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(storage=games.storage.OverwriteStorage(), upload_to='word/'),
        ),
    ]
