# Generated by Django 3.2.7 on 2021-10-10 22:09

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0004_alter_word_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/Users/cyrilhenry/Documents/PYTHON/school/school/content/media'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='wordfind',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
