# Generated by Django 3.2.7 on 2021-10-18 19:51

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_letterscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Halo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/Users/cyrilhenry/Documents/PYTHON/school/school/content/media'), upload_to='')),
            ],
        ),
    ]
