# Generated by Django 3.2.7 on 2022-01-24 16:23

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0011_additionposeescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halo',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\ENDTG\\Documents\\GitHub\\school\\school\\content\\media'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\ENDTG\\Documents\\GitHub\\school\\school\\content\\media'), upload_to=''),
        ),
        migrations.CreateModel(
            name='WordScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('level', models.CharField(max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
