# Generated by Django 3.2.7 on 2022-01-24 17:41

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20220124_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halo',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/Users/cyrilhenry/Documents/PYTHON/school/school/content/media'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/Users/cyrilhenry/Documents/PYTHON/school/school/content/media'), upload_to=''),
        ),
    ]
