# Generated by Django 3.2.7 on 2022-01-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('games', '0015_auto_20220125_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordone',
            options={'ordering': ('level', 'name'), 'verbose_name': 'Mot', 'verbose_name_plural': 'Mots'},
        ),
        migrations.RemoveField(
            model_name='wordone',
            name='group',
        ),
        migrations.AddField(
            model_name='wordone',
            name='group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
