# Generated by Django 3.2.7 on 2022-01-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20220125_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordfind',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wordfind',
            name='word',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.DeleteModel(
            name='WordFind',
        ),
    ]
