# Generated by Django 3.2.7 on 2022-04-04 18:54

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('answer_pic', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/Users/cyrilhenry/Documents/PYTHON/school/school/content/media'), upload_to='poll')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255, null=True)),
                ('mandatory', models.BooleanField(default=True)),
                ('choices', models.ManyToManyField(related_name='QuestionsChoices', to='poll.Answer')),
                ('correct', models.ManyToManyField(related_name='QuestionsCorrect', to='poll.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Public'), (3, 'Close')], default=1)),
                ('published', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(related_name='Quizs', to='poll.Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuizInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_quiz', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('complete', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.DateTimeField(auto_now_add=True)),
                ('time_taken_delta', models.DateTimeField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.question')),
                ('quiz_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.quizinstance')),
                ('response', models.ManyToManyField(related_name='UserResponses', to='poll.Answer')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.theme'),
        ),
    ]
