# Generated by Django 3.2.7 on 2022-05-18 08:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_pic',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\ENDTG\\Documents\\GitHub\\school\\school\\content\\media'), upload_to='poll'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_pic',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\ENDTG\\Documents\\GitHub\\school\\school\\content\\media'), upload_to='poll/'),
        ),
    ]
