# Generated by Django 3.2.7 on 2022-05-18 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20220518_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.theme'),
        ),
    ]
