# Generated by Django 3.2.7 on 2022-04-05 07:08

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_question_question_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_pic',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/cyrilhenry/Documents/PYTHON/school/school/content/media'), upload_to='poll/'),
        ),
    ]
