# Generated by Django 3.2.7 on 2022-04-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_alter_question_question_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='randomize',
            field=models.BooleanField(default=False),
        ),
    ]
