# Generated by Django 3.2.7 on 2023-02-13 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_alter_quiz_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='Questions', to='poll.Question'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.theme'),
        ),
        migrations.AlterField(
            model_name='quizinstance',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Quizs', to='poll.quiz'),
        ),
    ]
