# Generated by Django 3.2.7 on 2022-04-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20220405_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
