# Generated by Django 3.2.7 on 2022-04-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20220406_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='randomize',
            field=models.BooleanField(default=False),
        ),
    ]
