# Generated by Django 3.2.7 on 2022-04-07 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_question_randomize'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.quiz')),
            ],
        ),
    ]
