# Generated by Django 3.2.7 on 2022-04-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_questionorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='published',
            field=models.DateTimeField(null=True),
        ),
    ]
